# Generated by Django 5.2.4 on 2025-07-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='user',
        ),
    ]
